# Generated by Django 6.0.4 on 2026-07-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('color', '0001_initial'),
        ('items', '0004_alter_item_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_encontro',
        ),
        migrations.RemoveField(
            model_name='item',
            name='local_encontrado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='validado_por',
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.categoria'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='color.cor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('PERDIDO', 'Perdido'), ('AGUARDANDO_ENTREGA', 'Aguardando entrega'), ('NO_ESTOQUE', 'No estoque'), ('DISPONIVEL_PARA_DOACAO', 'Disponível para doação'), ('DEVOLVIDO', 'Devolvido'), ('DOADO', 'Doado')], max_length=30),
        ),
    ]
