# Generated by Django 6.0.4 on 2026-04-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('admin_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_doacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Doação',
                'verbose_name_plural': 'Sessões de Doação',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InteresseDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='items.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_doacao', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='donations.sessaodoacao')),
            ],
            options={
                'verbose_name': 'Interesse em Doação',
                'verbose_name_plural': 'Interesses em Doação',
                'unique_together': {('usuario', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('interesse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doacao', to='donations.interessedoacao')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='donations.sessaodoacao')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data_sorteio'],
            },
        ),
    ]
