# Generated by Django 6.0.4 on 2026-07-11 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0005_alter_item_options_remove_item_cadastrado_por_and_more'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('CORRESPONDENCIA_ENCONTRADA', 'Correspondência Encontrada'), ('SEM_CORRESPONDENCIA', 'Sem Correspondência')], default='PENDENTE', max_length=30)),
                ('justificativa', models.TextField()),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises', to=settings.AUTH_USER_MODEL)),
                ('item_encontrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_como_encontrado', to='items.item')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='report.reporte')),
            ],
        ),
    ]
