# Generated by Django 6.0.4 on 2026-07-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='reporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='report.reporte'),
        ),
    ]
