# Generated by Django 6.0.4 on 2026-07-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analise_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_confianca', models.PositiveSmallIntegerField(help_text='Score de 0 a 100 indicando o grau de confiança na melhor correspondência encontrada.')),
                ('convergencias', models.JSONField(default=dict, help_text='Pontos em que o item candidato bate com a descrição do item perdido.')),
                ('inconsistencias', models.JSONField(default=dict, help_text='Pontos em que o item candidato diverge da descrição do item perdido.')),
                ('recomendacao', models.TextField(help_text='Texto legível resumindo a sugestão do sistema para o admin.')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('data_prompt', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('analise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parecer', to='analysis.analise')),
            ],
            options={
                'verbose_name': 'Parecer',
                'verbose_name_plural': 'Pareceres',
            },
        ),
    ]
