# Generated by Django 6.0.4 on 2026-07-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_parecer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parecer',
            old_name='score_confianca',
            new_name='score_correspondencia',
        ),
    ]
