# Generated by Django 6.0.4 on 2026-04-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reivindicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_perda', models.DateField()),
                ('local_perda', models.CharField(max_length=200)),
                ('caracteristicas_especificas', models.TextField()),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada')], default='PENDENTE', max_length=20)),
                ('justificativa_admin', models.TextField(blank=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reivindicacoes', to='items.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reivindicacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reivindicação',
                'verbose_name_plural': 'Reivindicações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ParecerIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_confianca', models.FloatField()),
                ('convergencias', models.JSONField(default=list)),
                ('inconsistencias', models.JSONField(default=list)),
                ('recomendacao', models.TextField()),
                ('perguntas_sugeridas', models.JSONField(default=list)),
                ('prompt_utilizado', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('reivindicacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parecer_ia', to='claims.reivindicacao')),
            ],
            options={
                'verbose_name': 'Parecer da IA',
                'verbose_name_plural': 'Pareceres da IA',
            },
        ),
    ]
