# Generated by Django 6.0.4 on 2026-04-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('categoria', models.CharField(choices=[('ELETRONICO', 'Eletrônico'), ('DOCUMENTO', 'Documento'), ('VESTUARIO', 'Vestuário'), ('ACESSORIO', 'Acessório'), ('MATERIAL_ESCOLAR', 'Material Escolar'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(max_length=50)),
                ('local_encontrado', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('dados_sensiveis', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VALIDO', 'Válido'), ('ARMAZENADO', 'Armazenado'), ('DISPONIVEL_PARA_DOACAO', 'Disponível para Doação'), ('SORTEADO_AGUARDANDO_ENTREGA', 'Sorteado - Aguardando Entrega'), ('REIVINDICADO_AGUARDANDO_ENTREGA', 'Reivindicado - Aguardando Entrega'), ('ENTREGUE', 'Entregue'), ('DOADO', 'Doado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=35)),
                ('data_encontro', models.DateTimeField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_despacho', models.DateTimeField(blank=True, null=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
