# Generated by Django 6.0.4 on 2026-05-08 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cadastrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('ELETRONICO', 'Eletrônico'), ('DOCUMENTO', 'Documento'), ('VESTUARIO', 'Vestuário'), ('ACESSORIO', 'Acessório'), ('GARRAFA', 'Garrafa'), ('MATERIAL_ESCOLAR', 'Material Escolar'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
