# Generated by Django 6.0.4 on 2026-05-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_cadastrado_por_alter_item_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_encontro',
            field=models.DateField(),
        ),
    ]
